### ISSUE TITLE
Use servant-foreign

### ISSUE THREAD

**Issue by tfausak** [tfausak/lackey#3]
https://hackage.haskell.org/package/servant-foreign

**Comment by dredozubov** [comment]
`servant` 0.5 and `servant-foreign` were finally released, so.. bump. `servant-js` code can be a good example of how this can be updated.

**Comment by tfausak** [comment]
I got a lot of the work done in #4. It took me a while to figure out how all the new stuff works. All that needs to be done now is actually generate the code :smile:
