### ISSUE TITLE
Servant 0.15 support 

### ISSUE THREAD

**Issue by domenkozar** [tfausak/lackey#7]
Hey @tfausak this is one of the last packages blocking Servant 0.15 in stackage: https://github.com/commercialhaskell/stackage/pull/4139

**Comment by tfausak** [comment]
Oops, sorry about that! I fixed it in 1a9f7b675ba9510bec0b6fc7d5438fca537a3f40 and it should be released as version 1.0.7 shortly. Thanks for the report!
